const DestinationDetails=[
    {
     "Places": "Jodhpur",
     "Rankings": 1,
     "Cost for a Nomad($)": 450,
     "Wifi(Mbps)": 90,
     "Fun": 5,
     "Air Quality(AQI)": 150,
     "Safety": 4,
     "Electricity": 3,
     "Nightlife": 3,
     "Place for WFH": 3,
     "Avg. Trip time(days)": 3,
     "Safe for Women": 3,
     "Climate": "Warm",
     "Medical": 4
    },
    {
     "Places": "Goa",
     "Rankings": 2,
     "Cost for a Nomad($)": 1200,
     "Wifi(Mbps)": 130,
     "Fun": 5,
     "Air Quality(AQI)": 120,
     "Safety": 4,
     "Electricity": 3,
     "Nightlife": 5,
     "Place for WFH": 5,
     "Avg. Trip time(days)": 12,
     "Safe for Women": 4,
     "Climate": "Warm",
     "Medical": 4
    },
    {
     "Places": "Jaipur",
     "Rankings": 3,
     "Cost for a Nomad($)": 600,
     "Wifi(Mbps)": 20,
     "Fun": 3,
     "Air Quality(AQI)": 120,
     "Safety": 4,
     "Electricity": 4,
     "Nightlife": 5,
     "Place for WFH": 5,
     "Avg. Trip time(days)": 4,
     "Safe for Women": 4,
     "Climate": "Warm",
     "Medical": 5
    },
    {
     "Places": "Mysore",
     "Rankings": 4,
     "Cost for a Nomad($)": 600,
     "Wifi(Mbps)": 20,
     "Fun": 3,
     "Air Quality(AQI)": 60,
     "Safety": 4,
     "Electricity": 3,
     "Nightlife": 4,
     "Place for WFH": 5,
     "Avg. Trip time(days)": 14,
     "Safe for Women": 4,
     "Climate": "Warm",
     "Medical": 4
    },
    {
     "Places": "Chandigarh",
     "Rankings": 5,
     "Cost for a Nomad($)": 700,
     "Wifi(Mbps)": 20,
     "Fun": 3,
     "Air Quality(AQI)": 150,
     "Safety": 4,
     "Electricity": 4,
     "Nightlife": 5,
     "Place for WFH": 5,
     "Avg. Trip time(days)": 3,
     "Safe for Women": 5,
     "Climate": "Cold",
     "Medical": 5
    },
    {
     "Places": "McLeod Ganj",
     "Rankings": 6,
     "Cost for a Nomad($)": 1200,
     "Wifi(Mbps)": 40,
     "Fun": 2,
     "Air Quality(AQI)": 180,
     "Safety": 4,
     "Electricity": 3,
     "Nightlife": 3,
     "Place for WFH": 5,
     "Avg. Trip time(days)": 14,
     "Safe for Women": 4,
     "Climate": "Cold",
     "Medical": 3
    },
    {
     "Places": "Srinagar",
     "Rankings": 7,
     "Cost for a Nomad($)": 500,
     "Wifi(Mbps)": 20,
     "Fun": 2,
     "Air Quality(AQI)": 90,
     "Safety": 4,
     "Electricity": 3,
     "Nightlife": 3,
     "Place for WFH": 2,
     "Avg. Trip time(days)": 11,
     "Safe for Women": 3,
     "Climate": "Cold",
     "Medical": 3
    },
    {
     "Places": "Rishikesh",
     "Rankings": 8,
     "Cost for a Nomad($)": 700,
     "Wifi(Mbps)": 20,
     "Fun": 2,
     "Air Quality(AQI)": 180,
     "Safety": 4,
     "Electricity": 3,
     "Nightlife": 3,
     "Place for WFH": 5,
     "Avg. Trip time(days)": 14,
     "Safe for Women": 3,
     "Climate": "Warm",
     "Medical": 3
    },
    {
     "Places": "Guwhati",
     "Rankings": 9,
     "Cost for a Nomad($)": 500,
     "Wifi(Mbps)": 20,
     "Fun": 3,
     "Air Quality(AQI)": 170,
     "Safety": 4,
     "Electricity": 3,
     "Nightlife": 3,
     "Place for WFH": 5,
     "Avg. Trip time(days)": 6,
     "Safe for Women": 4,
     "Climate": "Warm",
     "Medical": 4
    },
    {
     "Places": "Delhi",
     "Rankings": 10,
     "Cost for a Nomad($)": 700,
     "Wifi(Mbps)": 40,
     "Fun": 4,
     "Air Quality(AQI)": 150,
     "Safety": 3,
     "Electricity": 3,
     "Nightlife": 5,
     "Place for WFH": 3,
     "Avg. Trip time(days)": 4,
     "Safe for Women": 3,
     "Climate": "Warm",
     "Medical": 5
    },
    {
     "Places": "Mumbai",
     "Rankings": 11,
     "Cost for a Nomad($)": 950,
     "Wifi(Mbps)": 20,
     "Fun": 4,
     "Air Quality(AQI)": 100,
     "Safety": 4,
     "Electricity": 3,
     "Nightlife": 5,
     "Place for WFH": 4,
     "Avg. Trip time(days)": 5,
     "Safe for Women": 3,
     "Climate": "Warm",
     "Medical": 5
    }
   ]

   export default DestinationDetails;